config/routes.rb
TddTweet::Application.routes.draw do
  resources :tweets
  root "tweets#index"

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  validates :author, presence: true
  validates :content, presence: true
  validates :content, length: { maximum: 140,
    message: "%{count} characters is the maximum allowed" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def new
    @tweet = Tweet.new
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def index
    @tweets = Tweet.all
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    
    if @tweet.save
      redirect_to @tweet
    else
      render 'new'
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:author, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TddTweet</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice %>
  <p class="alert alert-notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-error"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/tweets/_form.html.erb
<% if @tweet.errors.any? %>
        <div id="error_explanation">
          <%= pluralize(@tweet.errors.count, "error") %> prohibited
            this post from being saved:
          <ul>
          <% @tweet.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
          </div>
        <% end %>

<%= form_for @tweet do |f| %>

  <p>
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </p>
    
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>
    <%= f.submit %>
<% end %>

app/views/tweets/create.html.erb
<h1>Tweets#create</h1>
<p>Find me in app/views/tweets/create.html.erb</p>

app/views/tweets/index.html.erb
<h1> Home Tweet Home </h1>
<h4>Have Something to Say?</h4>
<p>Say it here</p>
<%= render 'tweets/form' %>
<hr>
<% @tweets.reverse.each do |tweet| %>
  Tweet: #<%= tweet.id%> <br>
  <%= tweet.content %> &nbsp <br>
  Crafted By: <%= tweet.author %>
  <hr>
<% end %>

app/views/tweets/new.html.erb
<h1>Have Something to Say?</h1>
<p>Say it below</p>
<%= render 'form' %>
<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
Here is your Tweet!
<p><%= @tweet.content %> </p> 
<p><%= @tweet.author %> </p>
<%= link_to 'Back', tweets_path %>